syntax = "proto3";
package broker;
option go_package = "distributed-event-log/internal/proto";

service BrokerService {
  rpc Produce(ProduceRequest) returns (ProduceResponse);
  rpc Consume(ConsumeRequest) returns (ConsumeResponse);
  rpc CommitOffset(CommitOffsetRequest) returns (CommitOffsetResponse);
  rpc FetchOffset(FetchOffsetRequest) returns (FetchOffsetResponse);
}

message ProduceRequest {
  string topic = 1;
  bytes key = 2;
  bytes value = 3;
  optional int32 partition = 4;
}

message ProduceResponse {
  uint64 offset = 1;
}

message ConsumeRequest {
  uint64 offset = 1;
  string topic = 2;
  optional int32 partition = 3;
}

message ConsumeResponse {
  uint64 offset = 1;
  bytes key = 2;
  bytes value = 3;
}

message CommitOffsetRequest {
  string group_id = 1;
  string topic = 2;
  int32 partition = 3;
  uint64 offset = 4;
}

message CommitOffsetResponse {}

message FetchOffsetRequest {
  string group_id = 1;
  string topic = 2;
  int32 partition = 3;
}

message FetchOffsetResponse {
  uint64 offset = 1;
}